services:
    inowas.modflowcalculation.calculation_list_projector:
        class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationListProjector
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowcalculation.calculation_results_projector:
        class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationResultsProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflowcalculation.calculation_configuration_projector:
        class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationConfigurationProjector
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@inowas.modflowmodel.manager'
          - '@inowas.soilmodel.manager'