services:
    inowas.modflowcalculation.configuration_persister:
        class: Inowas\ModflowCalculation\Service\ConfigurationPersister
        arguments: ['%data_folder%']

    inowas.modflowcalculation.amqp_flopy_calculation:
        class: Inowas\ModflowCalculation\Service\AMQPModflowCalculation
        arguments: ['@inowas.amqp.stream.connection', 'flopy_calculation_queue']

    inowas.modflowcalculation.amqp_flopy_calculation_listener:
        class: Inowas\ModflowCalculation\Service\AMQPModflowCalculationListener
        arguments: ['@inowas.amqp.stream.connection', 'flopy_calculation_finished_queue']

    inowas.modflowcalculation.amqp_flopy_calculation_read_data:
        class: Inowas\ModflowCalculation\Service\AMQPModflowCalculationReadData
        arguments: ['@inowas.amqp.stream.connection', 'rpc_flopy_read_data_queue']

    inowas.modflowcalculation.calculation_configuration_finder:
          class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationConfigurationFinder
          arguments:
            - '@doctrine.dbal.default_connection'

    inowas.modflowcalculation.calculation_results_finder:
        class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationResultsFinder
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@inowas.modflowcalculation.amqp_flopy_calculation_read_data'

    inowas.modflowcalculation.calculation_list_finder:
        class: Inowas\ModflowCalculation\Infrastructure\Projection\Calculation\CalculationListFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflowcalculation.stressperiod_data_generator:
        class: Inowas\ModflowCalculation\Service\StressPeriodDataGenerator
        arguments:
            - '@inowas.geotools.geotools_service'
