language: php

php:
  - '7.0'

addons:
  postgresql: "9.4"

before_script:
  - sudo apt-get update
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - psql -c 'create role travis SUPERUSER WITH PASSWORD 'travis';' -U postgres
  - psql -c 'create database travis_ci_db OWNER root;' -U postgres
  - psql -c 'create extension postgis;' -U postgres

# Handle git submodules yourself
git:
    submodules: false
