language: php

php:
  - '7.0'

addons:
  postgresql: "9.4"

before_script:
  - sudo apt-get update
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ./build/build.Linux.sh

# Handle git submodules yourself
git:
    submodules: false
