language: php

php:
  - '7.1'

addons:
  postgresql: "9.4"

before_script:
  - sudo apt-get update
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - composer dump-autoload -o
  - psql -c "create role travis_ci_user WITH PASSWORD 'travis' LOGIN SUPERUSER;" -U postgres
  - bin/console doctrine:database:create --env=test
  - psql travis_ci_db_test < "build/sql/structure.sql"
  - bin/console doctrine:schema:create --env=test

script:
  - mkdir -p build/logs
  - php bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php bin/coveralls -v

# Handle git submodules yourself
git:
    submodules: false
