services:
    inowas.modflowmodel.add_modflow_model_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\AddBoundaryHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.change_modflow_model_bounding_box_handler:
        class: Inowas\ModflowModel\Model\Handler\ChangeModflowModelBoundingBoxHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.change_modflow_model_description_handler:
        class: Inowas\ModflowModel\Model\Handler\ChangeModflowModelDescriptionHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.change_modflow_model_grid_size_handler:
        class: Inowas\ModflowModel\Model\Handler\ChangeModflowModelGridSizeHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.change_modflow_model_name_handler:
        class: Inowas\ModflowModel\Model\Handler\ChangeModflowModelNameHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.change_modflow_model_soilmodel_id_handler:
        class: Inowas\ModflowModel\Model\Handler\ChangeModflowModelSoilmodelIdHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.clone_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\CloneModflowModelHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.create_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\CreateModflowModelHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.geotools.geotools_service'

    inowas.modflowmodel.remove_modflow_model_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\RemoveBoundaryHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.update_modflow_model_area_geometry_handler:
        class: Inowas\ModflowModel\Model\Handler\UpdateAreaGeometryHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.update_modflow_model_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\UpdateBoundaryHandler
        arguments: ['@modflow_model_list']

    inowas.modflowmodel.update_modflow_model_boundary_geometry_handler:
        class: Inowas\ModflowModel\Model\Handler\UpdateBoundaryGeometryHandler
        arguments: ['@modflow_model_list']
