services:
    # ModflowBoundaryAggregate
    inowas.modflowmodel.add_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\AddBoundaryHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.add_boundary_observation_point_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\AddBoundaryObservationPointHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.clone_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\CloneBoundaryHandler
        arguments:
          - '@modflow_boundary_list'

    inowas.modflowmodel.remove_boundary_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\RemoveBoundaryHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.remove_boundary_observation_point_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\RemoveBoundaryObservationPointHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.update_boundary_active_cells_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryActiveCellsHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'
          - '@inowas.modflowmodel.boundary_manager'

    inowas.modflowmodel.update_boundary_affected_layers_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryActiveCellsHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'
          - '@inowas.modflowmodel.boundary_manager'

    inowas.modflowmodel.update_boundary_geometry_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryGeometryHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.update_boundary_metadata_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryMetadataHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.update_boundary_name_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryNameHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'

    inowas.modflowmodel.update_boundary_observation_point_handler:
        class: Inowas\ModflowModel\Model\Handler\Boundary\UpdateBoundaryObservationPointHandler
        arguments:
          - '@modflow_model_list'
          - '@modflow_boundary_list'


    # ModflowModelAggregate
    inowas.modflowmodel.calculate_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\CalculateModflowModelHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.modflow_packages_manager'
          - '@inowas.modflowmodel.amqp_modflow_calculation'

    inowas.modflowmodel.calculate_stress_periods_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\CalculateStressperiodsHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.manager'

    inowas.modflowmodel.change_bounding_box_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeBoundingBoxHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.geotools.geotools_service'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.change_description_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeDescriptionHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.change_flow_package_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeFlowPackageHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.change_grid_size_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeGridSizeHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.change_name_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeNameHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.change_soilmodel_id_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\ChangeSoilmodelIdHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.clone_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\CloneModflowModelHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.create_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\CreateModflowModelHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.geotools.geotools_service'

    inowas.modflowmodel.delete_modflow_model_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\DeleteModflowModelHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.update_area_active_cells_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateAreaActiveCellsHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.boundary_manager'

    inowas.modflowmodel.update_area_geometry_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateAreaGeometryHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.update_calculation_id_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateCalculationIdHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.update_calculation_results_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateCalculationResultsHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.update_length_unit_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateLengthUnitHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.update_modflow_package_parameter_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateModflowPackageParameterHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.update_stress_periods_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateStressPeriodsHandler
        arguments:
          - '@modflow_model_list'

    inowas.modflowmodel.update_time_unit_handler:
        class: Inowas\ModflowModel\Model\Handler\ModflowModel\UpdateTimeUnitHandler
        arguments:
          - '@modflow_model_list'
          - '@inowas.modflowmodel.model_finder'
