services:
    inowas.modflowmodel.model_boundaries_projector:
        class: Inowas\ModflowModel\Infrastructure\Projection\BoundaryList\BoundaryListProjector
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@inowas.geotools.geotools_service'
          - '@inowas.modflowmodel.model_finder'

    inowas.modflowmodel.model_boundary_values_projector:
        class: Inowas\ModflowModel\Infrastructure\Projection\BoundaryList\BoundaryValuesProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflowmodel.model_details_projector:
        class: Inowas\ModflowModel\Infrastructure\Projection\ModelList\ModelProjector
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@doctrine.orm.default_entity_manager'
          - '@inowas.geotools.geotools_service'