services:
    inowas.modflowmodel.amqp_modflow_calculation:
        class: Inowas\ModflowModel\Service\AMQPModflowCalculation
        arguments:
            - '@inowas.amqp.stream.connection'
            - '%rabbit_mq_calculation_queue%'

    inowas.modflowmodel.amqp_modflow_calculation_listener:
        class: Inowas\ModflowModel\Service\AMQPModflowCalculationListener
        arguments:
            - '@inowas.amqp.stream.connection'
            - '%rabbit_mq_calculation_finished_queue%'

    inowas.modflowmodel.amqp_read_data:
        class: Inowas\ModflowModel\Service\AMQPReadData
        arguments:
            - '@inowas.amqp.stream.connection'
            - '%rabbit_mq_read_data_queue%'

    inowas.modflowmodel.manager:
        class: Inowas\ModflowModel\Service\ModflowModelManager
        arguments:
            - '@inowas.modflowmodel.boundary_finder'
            - '@inowas.modflowmodel.model_finder'
            - '@inowas.modflowmodel.stressperiod_data_generator'

    inowas.modflowmodel.modflow_packages_manager:
        class: Inowas\ModflowModel\Service\ModflowPackagesManager
        arguments:
            - '@inowas.modflowmodel.modflow_packages_persister'
            - '@modflow_model_list'
            - '@inowas.modflowmodel.manager'
            - '@inowas.soilmodel.manager'

    inowas.modflowmodel.modflow_packages_persister:
        class: Inowas\ModflowModel\Service\ModflowPackagesPersister
        arguments:
            - '%data_folder%'

    inowas.modflowmodel.stressperiod_data_generator:
        class: Inowas\ModflowModel\Service\StressPeriodDataGenerator
        arguments:
            - '@inowas.geotools.geotools_service'
