services:
    inowas.modflowmodel.manager:
        class: Inowas\ModflowModel\Service\ModflowModelManager
        arguments:
            - '@inowas.modflowmodel.boundaries_finder'
            - '@inowas.modflowmodel.model_finder'
            - '@inowas.modflowcalculation.stressperiod_data_generator'

    inowas.modflowmodel.boundaries_finder:
        class: Inowas\ModflowModel\Infrastructure\Projection\BoundaryList\BoundaryFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflowmodel.model_finder:
        class: Inowas\ModflowModel\Infrastructure\Projection\ModelList\ModelFinder
        arguments:
          - '@doctrine.dbal.default_connection'
