services:
    inowas.modflow_projection.soilmodel_list:
        class: Inowas\Soilmodel\Projection\SoilmodelList\SoilmodelListProjector
        arguments:
          - '@doctrine.dbal.default_connection'
