prooph_service_bus:
    command_buses:
        soil_model_command_bus:
            plugins:
                - 'prooph_event_store_bus_bridge.transaction_manager'
            router:
                type: 'prooph_service_bus.command_bus_router'
                routes:
                    'Inowas\Soilmodel\Model\Command\AddBoreLogToSoilmodel': 'inowas.soilmodel.add_borelog_to_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\AddGeologicalLayerToSoilmodel': 'inowas.soilmodel.add_geological_layer_to_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\ChangeSoilmodelDescription': 'inowas.soilmodel.change_soilmodel_description.handler'
                    'Inowas\Soilmodel\Model\Command\ChangeSoilmodelName': 'inowas.soilmodel.change_soilmodel_name.handler'
                    'Inowas\Soilmodel\Model\Command\CreateSoilmodel': 'inowas.soilmodel.create_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\DeleteSoilmodel': 'inowas.soilmodel.delete_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\InterpolateLayer': 'inowas.soilmodel.interpolate_layer.handler'
                    'Inowas\Soilmodel\Model\Command\RemoveBoreLogFromSoilmodel': 'inowas.soilmodel.remove_borelog_layer_from_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\RemoveGeologicalLayerFromSoilmodel': 'inowas.soilmodel.remove_geological_layer_from_soilmodel.handler'
                    'Inowas\Soilmodel\Model\Command\AddHorizonToBoreLog': 'inowas.soilmodel.add_horizon_to_borelog.handler'
                    'Inowas\Soilmodel\Model\Command\RemoveHorizonFromBoreLog': 'inowas.soilmodel.remove_horizon_from_borelog.handler'
                    'Inowas\Soilmodel\Model\Command\ChangeBoreLogLocation': 'inowas.soilmodel.change_borelog_location.handler'
                    'Inowas\Soilmodel\Model\Command\ChangeBoreLogName': 'inowas.soilmodel.change_borelog_name.handler'
                    'Inowas\Soilmodel\Model\Command\CreateBoreLog': 'inowas.soilmodel.create_borelog.handler'
                    'Inowas\Soilmodel\Model\Command\DeleteBoreLog': 'inowas.soilmodel.delete_borelog.handler'
    event_buses:
        soilmodel_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'
                routes:
                    'Inowas\Soilmodel\Model\Event\SoilmodelWasCreated':
                        - 'inowas.projector.soilmodel_list'
