imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@InowasAppBundle/Resources/config/services.xml" }
    - { resource: "@InowasGeoToolsBundle/Resources/config/services.xml" }
    - { resource: "@InowasModflowBundle/Resources/config/services.xml" }
    - { resource: "@InowasSoilmodelBundle/Resources/config/services.yml" }
    - { resource: "@InowasScenarioAnalysisBundle/Resources/config/services.xml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: SFSESSID
    fragments:       ~
    http_method_override: true
    assets: ~
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

        types:
            geometry:                     CrEOF\Spatial\DBAL\Types\GeometryType
            point:                        CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:                      CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring:                   CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

            active_cells:                 Inowas\ModflowBundle\Model\Type\ActiveCellsType
            bounding_box:                 Inowas\ModflowBundle\Model\Type\BoundingBoxType
            calculation_properties:       Inowas\ModflowBundle\Model\Type\CalculationPropertiesType
            grid_size:                    Inowas\ModflowBundle\Model\Type\GridSizeType
            time_unit:                    Inowas\ModflowBundle\Model\Type\TimeUnitType

            chd_stress_period:            Inowas\ModflowBundle\Model\Type\ChdStressPeriodsType
            ghb_stress_period:            Inowas\ModflowBundle\Model\Type\GhbStressPeriodsType
            rch_stress_period:            Inowas\ModflowBundle\Model\Type\RchStressPeriodsType
            riv_stress_period:            Inowas\ModflowBundle\Model\Type\RivStressPeriodsType
            wel_stress_period:            Inowas\ModflowBundle\Model\Type\WelStressPeriodsType

            property_type:                Inowas\SoilmodelBundle\Type\PropertyTypeType
            soilmodel_property_type:      Inowas\SoilmodelBundle\Type\PropertyTypeType
            soilmodel_property_value:     Inowas\SoilmodelBundle\Type\PropertyValueType
            uuid:                         Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle:
                        type: xml
                        prefix: AppBundle\Entity
                    InowasAppBundle:
                        type: xml
                        prefix: Inowas\AppBundle\Model
                    InowasSoilmodelBundle:
                        type: xml
                        prefix: Inowas\SoilmodelBundle\Model
                    InowasModflowBundle:
                        type: xml
                        prefix: Inowas\ModflowBundle\Model
                    InowasScenarioAnalysisBundle:
                        type: xml
                        prefix: Inowas\ScenarioAnalysisBundle\Model

                dql:
                    numeric_functions:
                        st_area:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                        st_asgeojson:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsGeoJson
                        st_envelope:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STEnvelope
                        st_geomfromtext:  CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                        st_intersects:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersects
                        st_makeline:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                        st_point:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                        st_setsrid:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSetSRID
                        st_transform:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STTransform

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Inowas\AppBundle\Model\User

# FOS RestBundle Configuration
fos_rest:
    view:
        view_response_listener: true

    routing_loader:
        default_format: json

    param_fetcher_listener: true

# Nelmio apiDoc configuration
nelmio_api_doc: ~

# Nelmio cors configuration
nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']

# JMS Serializer configuration
jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                path: "%kernel.root_dir%/Resources/FOSUserBundle/serializer"
                namespace_prefix: "FOS\\UserBundle"

# Inowas configuration
inowas_pyprocessing:
    prefix:               "python"
    api_base_url:         "http://localhost/api"
    data_folder:          "%kernel.root_dir%/../var/data"
    temp_folder:          "%kernel.root_dir%/../var/tmp"
    pyprocessing_folder:  "%kernel.root_dir%/../py/pyprocessing"
    max_processes:    5
