imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%_test"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

parameters:
    inowas.geotiff.data_folder:  '%kernel.root_dir%/../tests/data/geotiff'