NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

InowasModflowBundle:
    resource: "@InowasModflowBundle/Resources/config/routing.yml"

InowasAppBundle:
    resource: "@InowasAppBundle/Resources/config/routing.yml"
