# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    inowas.interpolation:
        class: AppBundle\Service\Interpolation
        arguments: ['@serializer', '@kernel']

    inowas.modflow:
        class: AppBundle\Service\Modflow
        arguments: ['@doctrine.orm.default_entity_manager', '@inowas.interpolation']

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
