# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    inowas.modflow.data_folder:  ../py/pyprocessing/data/modflow

services:
    inowas.interpolation:
        class: AppBundle\Service\Interpolation
        arguments: ['@kernel', '@inowas.interpolation.configurationfile.creator']

    inowas.interpolation.configurationfile.creator:
        class: AppBundle\Service\InterpolationConfigurationFileCreator
        arguments: ['@kernel', '@serializer']

    inowas.propertytypes:
        class: AppBundle\Service\PropertyTypes
        arguments: []

    inowas.geotools:
        class: AppBundle\Service\GeoTools
        arguments: ['@doctrine.orm.default_entity_manager']

    inowas.modflow:
        class: AppBundle\Service\Modflow
        arguments: ['@serializer', '@kernel', '@inowas.python_process', '%inowas.modflow.working_directory%', '%inowas.modflow.data_folder%', '%inowas.temp_folder%', '%inowas.modflow.api_base_url%']

    inowas.geoimage:
        class: AppBundle\Service\GeoImage
        arguments: ['@serializer', '@kernel', '@inowas.python_process', '%inowas.geotiff.working_directory%', '%inowas.geotiff.data_folder%', '%inowas.temp_folder%']

    inowas.soilmodel:
        class: AppBundle\Service\SoilModelService
        arguments: ['@doctrine.orm.default_entity_manager', '@inowas.interpolation']

    inowas.python_process:
        class: AppBundle\Service\PythonProcess
        arguments: ['%inowas.python_process.prefix%']

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
