# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    inowas.modflow.data_folder:  ../py/pyprocessing/data/modflow

services:
    inowas.process.interpolation:
        class: AppBundle\Service\Interpolation
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.process.configurationfilecreatorfactory:
        class: AppBundle\Service\ConfigurationFileCreatorFactory
        arguments: ['@kernel', '@serializer']

    inowas.propertytypes:
        class: AppBundle\Service\PropertyTypes
        arguments: []

    inowas.geotools:
        class: AppBundle\Service\GeoTools
        arguments: ['@doctrine.orm.default_entity_manager']

    inowas.modflow:
        class: AppBundle\Service\Modflow
        arguments: ['@serializer', '@kernel', '@inowas.python_process', '%inowas.modflow.working_directory%', '%inowas.modflow.data_folder%', '%inowas.temp_folder%', '%inowas.modflow.api_base_url%']

    inowas.geoimage:
        class: AppBundle\Service\GeoImage
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.soilmodel:
        class: AppBundle\Service\SoilModelService
        arguments: ['@doctrine.orm.default_entity_manager', '@inowas.process.interpolation']

    inowas.python_process:
        class: AppBundle\Service\PythonProcess
        arguments: ['%inowas.python_process.prefix%']

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
