services:

    inowas.modflow:
        class: InowasPyprocessingBundle\Service\Modflow
        arguments: ['@doctrine.orm.entity_manager', '@inowas.modflow.processbuilder']

    inowas.modflow.processbuilder:
        class: InowasPyprocessingBundle\Service\ModflowProcessBuilder
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.modflow.servicerunner:
        class: InowasPyprocessingBundle\Service\ModflowServiceRunner
        arguments: ['@doctrine.orm.entity_manager', '@inowas.modflow.processbuilder', '%inowas.modflow.max_processes%']

    inowas.process.interpolation:
        class: InowasPyprocessingBundle\Service\Interpolation
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.process.configurationfilecreatorfactory:
        class: InowasPyprocessingBundle\Service\ConfigurationFileCreatorFactory
        arguments: ['@kernel', '@serializer']

    inowas.geoimage:
        class: InowasPyprocessingBundle\Service\GeoImage
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']