imports:
    - { resource: common/services.yml }

    - { resource: eventStore/event_store.yml }
    - { resource: serviceBus/service_bus.yml }

    - { resource: geoTools/services.yml }

    - { resource: modflowBoundary/commandHandler.yml }
    - { resource: modflowBoundary/processManager.yml }
    - { resource: modflowBoundary/projections.yml }
    - { resource: modflowBoundary/services.yml }

    - { resource: modflowModel/commandHandler.yml }
    - { resource: modflowModel/processManager.yml }
    - { resource: modflowModel/projections.yml }
    - { resource: modflowModel/services.yml }

    - { resource: scenarioAnalysis/commandHandler.yml }
    - { resource: scenarioAnalysis/processManager.yml }
    - { resource: scenarioAnalysis/projections.yml }
    - { resource: scenarioAnalysis/services.yml }

    - { resource: soilmodel/commandHandler.yml }
    - { resource: soilmodel/projections.yml }
    - { resource: soilmodel/services.yml }

    - { resource: tool/projections.yml }
    - { resource: tool/services.yml }
