services:
    inowas.modflow_projection.model_scenarios:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioListProjector
        arguments:
          - '@doctrine.dbal.default_connection'
    inowas.model_scenarios_finder:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioFinder
        arguments:
          - '@doctrine.dbal.default_connection'
    inowas.modflow_projection.model_calculations:
        class: Inowas\Modflow\Projection\Calculation\CalculationsProjector
