services:
    inowas.modflow_projection.model_scenarios:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioListProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.model_scenarios_finder:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.model_boundaries:
        class: Inowas\Modflow\Projection\BoundaryList\BoundaryListProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.model_boundaries_finder:
        class: Inowas\Modflow\Projection\BoundaryList\BoundaryFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.calculation_results:
        class: Inowas\Modflow\Projection\Calculation\CalculationResultsProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.calculation_results_finder:
        class: Inowas\Modflow\Projection\Calculation\CalculationResultsFinder
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@inowas.modflow.file_persister'

    inowas.modflow_projection.calculation_budgets:
        class: Inowas\Modflow\Projection\Calculation\CalculationBudgetsProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.calculation_budgets_finder:
        class: Inowas\Modflow\Projection\Calculation\CalculationBudgetFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.calculation_list:
        class: Inowas\Modflow\Projection\Calculation\CalculationListProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.calculation_list_finder:
        class: Inowas\Modflow\Projection\Calculation\CalculationListFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.model_details:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelDetailsProjector
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@doctrine.orm.default_entity_manager'

    inowas.modflow_projection.model_details_finder:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelDetailsFinder
        arguments:
          - '@doctrine.dbal.default_connection'
