services:
    inowas.modflow_projection.model_scenarios:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioListProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.model_scenarios_finder:
        class: Inowas\Modflow\Projection\ModelScenarioList\ModelScenarioFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.boundaries:
        class: Inowas\Modflow\Projection\BoundaryList\BoundaryListProjector
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.model_boundaries_finder:
        class: Inowas\Modflow\Projection\BoundaryList\BoundaryFinder
        arguments:
          - '@doctrine.dbal.default_connection'

    inowas.modflow_projection.model_calculations:
        class: Inowas\Modflow\Projection\Calculation\CalculationsProjector
