rest_modflow_area:
    type: rest
    resource: '@InowasModflowBundle/Controller/AreaController.php'

rest_modflow_boundary:
    type: rest
    resource: '@InowasModflowBundle/Controller/BoundaryController.php'

rest_modflow_heads:
    type: rest
    resource: '@InowasModflowBundle/Controller/HeadsController.php'

rest_modflow:
    type: rest
    resource: '@InowasModflowBundle/Controller/ModelController.php'

rest_modflow_observationpoint:
    type: rest
    resource: '@InowasModflowBundle/Controller/ObservationPointController.php'

rest_modflow_stressperiod:
    type: rest
    resource: '@InowasModflowBundle/Controller/StressPeriodController.php'

rest_modflow_calculation:
    type: rest
    resource: '@InowasModflowBundle/Controller/CalculationsController.php'
