rest_message_box_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/MessageBoxController.php'
    prefix:    /v2

rest_calculation_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ModflowCalculationController.php'
    prefix:    /v2

rest_calculation_image_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ModflowCalculationImageController.php'
    prefix:    /image

rest_modflowmodel_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ModflowModelController.php'
    prefix:    /v2

rest_project_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ToolController.php'
    prefix:    /v2

rest_soilmodel_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/SoilmodelController.php'
    prefix:    /v2

rest_scenario_analysis_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ScenarioAnalysisController.php'
    prefix:    /v2
