rest_modflowmodel_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ModflowModelController.php'
    prefix:    /api

rest_scenario_analysis_api:
    type: rest
    resource: '@InowasModflowBundle/Controller/ScenarioAnalysisController.php'
    prefix:    /api/scenarioanalysis

rest_scenario_analysis_image:
    type: rest
    resource: '@InowasModflowBundle/Controller/ScenarioAnalysisImageController.php'
    prefix:    /image/scenarioanalysis

