prooph_service_bus:
    command_buses:
        modflow_command_bus:
            plugins:
                - 'prooph_event_store_bus_bridge.transaction_manager'
            router:
                type: 'prooph_service_bus.command_bus_router'
                routes:
                    'Inowas\Modflow\Model\Command\AddBoundary': 'inowas.add_modflow_model_boundary_handler'
                    'Inowas\Modflow\Model\Command\UpdateBoundary': 'inowas.update_modflow_model_boundary_handler'
                    'Inowas\Modflow\Model\Command\ChangeModflowModelBoundingBox': 'inowas.change_modflow_model_bounding_box_handler'
                    'Inowas\Modflow\Model\Command\ChangeModflowModelDescription': 'inowas.change_modflow_model_description_handler'
                    'Inowas\Modflow\Model\Command\ChangeModflowModelGridSize': 'inowas.change_modflow_model_grid_size_handler'
                    'Inowas\Modflow\Model\Command\ChangeModflowModelName': 'inowas.change_modflow_model_name_handler'
                    'Inowas\Modflow\Model\Command\ChangeModflowModelSoilmodelId': 'inowas.change_modflow_model_soilmodel_id_handler'
                    'Inowas\Modflow\Model\Command\CreateModflowModel': 'inowas.create_modflow_model_handler'
                    'Inowas\Modflow\Model\Command\AddModflowScenario': 'inowas.add_modflow_scenario_handler'
                    'Inowas\Modflow\Model\Command\RemoveModflowScenario': 'inowas.remove_modflow_scenario_handler'
                    'Inowas\Modflow\Model\Command\RemoveBoundary': 'inowas.remove_modflow_model_boundary_handler'
                    'Inowas\Modflow\Model\Command\CreateModflowModelCalculation': 'inowas.create_modflow_calculation_handler'
                    'Inowas\Modflow\Model\Command\AddResultToCalculation': 'inowas.add_result_to_calculation_handler'

    event_buses:
        modflow_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'
                routes:
                    'Inowas\Modflow\Model\Event\ModflowModelWasCreated':
                        - 'inowas.modflow_projection.model_scenarios'
                        - 'inowas.modflow_projection.calculation_results'

                    'Inowas\Modflow\Model\Event\ModflowModelNameWasChanged':
                        - 'inowas.modflow_projection.model_scenarios'

                    'Inowas\Modflow\Model\Event\ModflowModelDescriptionWasChanged':
                        - 'inowas.modflow_projection.model_scenarios'

                    'Inowas\Modflow\Model\Event\ModflowScenarioWasAdded':
                        - 'inowas.modflow_projection.boundaries'
                        - 'inowas.modflow_projection.model_scenarios'

                    'Inowas\Modflow\Model\Event\ModflowScenarioNameWasChanged':
                        - 'inowas.modflow_projection.model_scenarios'

                    'Inowas\Modflow\Model\Event\ModflowScenarioDescriptionWasChanged':
                        - 'inowas.modflow_projection.model_scenarios'

                    'Inowas\Modflow\Model\Event\ModflowCalculationResultWasAdded':
                        - 'inowas.modflow_projection.model_calculations'

                    'Inowas\Modflow\Model\Event\BoundaryWasAdded':
                        - 'inowas.modflow_projection.boundaries'
                        - 'inowas.modflow_projection.calculation_results'

                    'Inowas\Modflow\Model\Event\BoundaryWasAddedToScenario':
                        - 'inowas.modflow_projection.boundaries'

                    'Inowas\Modflow\Model\Event\BoundaryWasRemoved':
                        - 'inowas.modflow_projection.boundaries'

                    'Inowas\Modflow\Model\Event\BoundaryWasRemovedFromScenario':
                        - 'inowas.modflow_projection.boundaries'

                    'Inowas\Modflow\Model\Event\ModflowCalculationWasCreated':
                        - 'inowas.modflow_projection.calculation_results'

                    'Inowas\Modflow\Model\Event\ModflowCalculationResultWasAdded':
                        - 'inowas.modflow_projection.calculation_results'
