services:

    inowas.modflow:
        class: Inowas\ModflowBundle\Service\Modflow
        arguments: ['@doctrine.orm.entity_manager', '@inowas.modflow.processbuilder']

    inowas.modflow.processbuilder:
        class: Inowas\ModflowBundle\Service\ModflowProcessBuilder
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']