rest_scenario_analysis:
    type: rest
    resource: '@InowasScenarioAnalysisBundle/Controller/ScenarioAnalysisController.php'
    prefix:    /api/scenarioanalysis

rest_scenario_analysis_scenario:
    type: rest
    resource: '@InowasScenarioAnalysisBundle/Controller/ScenarioController.php'
    prefix:    /api/scenarioanalysis

rest_scenario_analysis_calculation:
    type: rest
    resource: '@InowasScenarioAnalysisBundle/Controller/CalculationsController.php'
    prefix:    /api/scenarioanalysis

rest_scenario_head_image:
    type: rest
    resource: '@InowasScenarioAnalysisBundle/Controller/ScenarioHeadsImageController.php'
    prefix:    /image/scenarioanalysis
