services:

    inowas.flopy:
        class: Inowas\PyprocessingBundle\Service\Flopy
        arguments: ['@doctrine.orm.entity_manager', '%inowas.pyprocessing_folder%']

    inowas.modflow:
        class: Inowas\PyprocessingBundle\Service\Modflow
        arguments: ['@doctrine.orm.entity_manager', '@inowas.modflow.processbuilder']

    inowas.modflow.processbuilder:
        class: Inowas\PyprocessingBundle\Service\ModflowProcessBuilder
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.flopy.servicerunner:
        class: Inowas\PyprocessingBundle\Service\FlopyServiceRunner
        arguments: ['@doctrine.orm.entity_manager', '@inowas.flopy', '%inowas.modflow.max_processes%']

    inowas.process.interpolation:
        class: Inowas\PyprocessingBundle\Service\Interpolation
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']

    inowas.process.configurationfilecreatorfactory:
        class: Inowas\PyprocessingBundle\Service\ConfigurationFileCreatorFactory
        arguments: ['@kernel', '@serializer']

    inowas.geoimage:
        class: Inowas\PyprocessingBundle\Service\GeoImage
        arguments: ['@kernel', '@inowas.process.configurationfilecreatorfactory']