services:

    inowas.scenarioanalysis.clone_scenarioanalysis_handler:
        class: Inowas\ScenarioAnalysis\Model\Handler\CloneScenarioAnalysisHandler
        arguments:
          - '@scenarioanalysis_list'
          - '@prooph_service_bus.modflow_command_bus'

    inowas.scenarioanalysis.create_scenario_handler:
        class: Inowas\ScenarioAnalysis\Model\Handler\CreateScenarioHandler
        arguments:
          - '@scenarioanalysis_list'
          - '@prooph_service_bus.modflow_command_bus'

    inowas.scenarioanalysis.create_scenarioanalysis_handler:
        class: Inowas\ScenarioAnalysis\Model\Handler\CreateScenarioAnalysisHandler
        arguments: ['@scenarioanalysis_list']

    inowas.scenarioanalysis.remove_scenario_handler:
        class: Inowas\ScenarioAnalysis\Model\Handler\RemoveScenarioHandler
        arguments:
          - '@scenarioanalysis_list'
          - '@prooph_service_bus.modflow_command_bus'