services:
    inowas.amqp.stream.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments: ['%rabbit_mq_host%', '%rabbit_mq_port%', '%rabbit_mq_user%', '%rabbit_mq_password%', '%rabbit_mq_vhost%']
