prooph_event_store:
    stores:
        modflow_model_store:
            adapter: 'prooph_event_store.doctrine_adapter.model_store'
            repositories:
                modflow_calculation_list:
                    repository_class: 'Inowas\ModflowCalculation\Infrastructure\Repository\EventStoreModflowCalculationList'
                    aggregate_type: 'Inowas\ModflowCalculation\Model\ModflowCalculationAggregate'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                modflow_model_list:
                    repository_class: 'Inowas\ModflowModel\Infrastructure\Repository\EventStoreModflowModelList'
                    aggregate_type: 'Inowas\ModflowModel\Model\ModflowModelAggregate'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                scenarioanalysis_list:
                    repository_class: 'Inowas\ScenarioAnalysis\Infrastructure\Repository\EventStoreScenarioAnalysisList'
                    aggregate_type: 'Inowas\ScenarioAnalysis\Model\ScenarioAnalysisAggregate'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                soil_model_list:
                    repository_class: 'Inowas\Soilmodel\Infrastructure\Repository\EventStoreSoilmodelList'
                    aggregate_type: 'Inowas\Soilmodel\Model\SoilmodelAggregate'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                bore_log_list:
                    repository_class: 'Inowas\Soilmodel\Infrastructure\Repository\EventStoreBoreLogList'
                    aggregate_type: 'Inowas\Soilmodel\Model\BoreLogAggregate'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'

services:
    prooph_event_store.doctrine_adapter.model_store:
        class: Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter
        arguments: ['@database_connection', '@prooph_event_store.message_factory', '@prooph_event_store.message_converter', '@prooph_event_store.payload_serializer', '%prooph_event_store.stream_table_map%']

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    prooph_event_store_bus_bridge.transaction_manager:
        class: Prooph\EventStoreBusBridge\TransactionManager
        tags:
            - { name: 'prooph_event_store.modflow_model_store.plugin' }

    prooph_event_store_bus_bridge.todo_event_publisher:
          class: Prooph\EventStoreBusBridge\EventPublisher
          arguments: ['@prooph_service_bus.modflow_event_bus']
          tags:
            - { name: 'prooph_event_store.modflow_model_store.plugin' }
